annotations:
  category: CMS
apiVersion: v2
appVersion: 6.1.1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - name: memcached
    condition: memcached.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 6.x.x
description: Web publishing platform for building blogs and websites.
home: https://artifacthub.io/packages/helm/gh-shesselink81-public/wordpress-apache
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
maintainers:
- email: sander@hesselink.me
  name: shesselink81
name: wordpress-apache
sources:
- https://github.com/shesselink81/helm-charts/tree/main/wordpress-apache
- https://github.com/shesselink81/wordpress-apache
- http://www.wordpress.com/
type: application
version: 2.1.10
