annotations:
  category: CMS
apiVersion: v2
appVersion: 6.2.2
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - name: memcached
    condition: memcached.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 6.x.x
description: Web publishing platform for building blogs and websites.
engine: gotpl
name: wordpress-nginx
type: application
home: https://artifacthub.io/packages/helm/helm-charts-home/wordpress-nginx
sources:
  - https://github.com/shesselink81/wordpress-nginx
  - http://www.wordpress.com/
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
version: 5.0.2
maintainers:
  - email: sander@hesselink.me
    name: shesselink81
